version: "3"

services:
  load-balancer:
    build: ./load-balancer
    ports:
      - "${LOAD_BALANCER_SERVER_PORT}:${LOAD_BALANCER_SERVER_PORT}"
    volumes:
      - ./load-balancer:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # depends_on:
    #   - server1
    #   - server2
    #   - server3

  # server1:
  #   build: ./server
  #   ports:
  #     - "${FIRST_SERVER_PORT}:${FIRST_SERVER_PORT}"
  #   environment:
  #     - PORT=${FIRST_SERVER_PORT}
  #     - SERVER_NAME=${FIRST_SERVER_NAME}
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules

  # server2:
  #   build: ./server
  #   ports:
  #     - "${SECOND_SERVER_PORT}:${SECOND_SERVER_PORT}"
  #   environment:
  #     - PORT=${SECOND_SERVER_PORT}
  #     - SERVER_NAME=${SECOND_SERVER_NAME}
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules

  # server3:
  #   build: ./server
  #   ports:
  #     - "${THIRD_SERVER_PORT}:${THIRD_SERVER_PORT}"
  #   environment:
  #     - PORT=${THIRD_SERVER_PORT}
  #     - SERVER_NAME=${THIRD_SERVER_NAME}
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules
